version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: produtoseletronicos
      MYSQL_USER: italo
      MYSQL_PASSWORD: "2610!!"
    command:
      --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  app:
    build: .
    container_name: java-app
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/produtoseletronicos?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: italo
      SPRING_DATASOURCE_PASSWORD: "2610!!"

volumes:
  mysql-data:
